name: christmas-music-carousel
version: '1.0'
summary: Play midi christmas music and connect to your Pi to display leds!
description: |
  This snap plays midi christmas music. You can select your own songs or play
  the default carousel selection via its embedded synthetizer.
  It can as well forward events via the network to a raspberry pi with PiGlow
  to light leds in sync with the music.
  /!\ This snap won't work on any board where alsa isn't installed by default
  for now.
grade: stable
confinement: devmode

apps:
  christmas-music-carousel:
    command: christmas-music-carousel

parts:
  christmas-music-carousel:
    source: christmas-music-carousel/
    plugin: go
    go-importpath: github.com/ubuntu/christmas-music-carousel
  music-grpc-events:
    source: music-grpc-events/
    plugin: python
    python-version: python2
    requirements: requirements.txt
    build-packages: [libasound2-dev, swig, swig3.0]
  midi-musics:
    source: musics/
    plugin: dump
    organize:
      '*mid' : musics/
  timidity-alsa:
    plugin: nil
    stage-packages: [alsa-utils, freepats, timidity]
  timidity-config:
    source: .
    plugin: dump
    stage: [timidity-snap.cfg]
    snap: [timidity-snap.cfg]
  # workaround https://bugs.launchpad.net/snapcraft/+bug/1648039
  workaround:
    source: https://github.com/ubuntu/christmas-music-carousel-snap/releases/download/v1.0/alsa-binding.tar.xz
    plugin: dump
    organize:
      sequencer_alsa.py: lib/python2.7/site-packages/midi/sequencer/
    after: [music-grpc-events]
